server:
  port: 8083
spring:
  application:
    name: search-service
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.158.133:9300
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    username: root
    password: 116184
  rabbitmq:
    host: 192.168.158.131
    username: itke
    password: 123
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    #register-with-eureka: false
    #fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

